/**
 * Every route in the application, in one place. Nothing in the UI hard-codes a path string:
 * a route rename is one edit here, and a typo is a compile error rather than a dead link.
 * Mirrors docs/09-ui-pages.md.
 */

export const ROUTES = {
  marketing: {
    home: '/',
    howItWorks: '/how-it-works',
    ourTradingSystem: '/our-trading-system',
    performance: '/performance',
    /** Synthetic 4-year demo/backtest explorer for marketing walkthroughs. */
    historicalPerformance: '/historical-performance',
    transparency: '/transparency',
    security: '/security',
    technology: '/technology',
    investors: '/investors',
    resources: '/resources',
    about: '/about',
    faq: '/faq',
    contact: '/contact',
    legal: {
      terms: '/legal/terms',
      privacy: '/legal/privacy',
      riskDisclosure: '/legal/risk-disclosure',
      refundPolicy: '/legal/refund-policy',
    },
  },

  auth: {
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    verifyEmail: '/verify-email',
    verifyEmailSent: '/verify-email/sent',
    oauthCallback: '/oauth/callback',
    /** Multi-step investor onboarding after email verification. */
    onboarding: '/onboarding',
  },

  dashboard: {
    root: '/dashboard',
    /** Full withdrawal flow (home → destination → review → OTP). */
    withdraw: '/withdraw',
    withdrawHistory: '/withdraw/history',
    /** Wallet Center — balances and history; deposit/withdraw route to dedicated pages. */
    wallet: '/wallet',
    /** Full deposit submission flow (amount, method, proof). */
    deposit: '/deposit',
    depositHistory: '/deposit/history',
    /** Browser return after OxaPay checkout — never credits funds. */
    depositOxapayReturn: '/deposit/oxapay/return',
    trades: '/trades',
    trade: (tradeId: string) => `/trades/${tradeId}`,
    // `/performance` belongs to the public marketing track record, which is SEO-critical and
    // externally linked. The investor's own performance therefore lives at a distinct path —
    // two route groups cannot both resolve `/performance`.
    performance: '/my-performance',
    transactions: '/transactions',
    notifications: '/notifications',
    referrals: '/referrals',
    /** Public progress-share landing (requires signed token query). */
    progressShare: '/progress-share',
    support: '/support',
    settings: {
      profile: '/settings/profile',
      security: '/settings/security',
      payoutMethods: '/settings/payout-methods',
      preferences: '/settings/preferences',
      emails: '/settings/emails',
    },
  },

  admin: {
    root: '/admin',
    login: '/admin/login',
    users: '/admin/users',
    newUser: '/admin/users/new',
    user: (userId: string) => `/admin/users/${userId}`,
    userHistory: (userId: string) => `/admin/users/${userId}/history`,
    kyc: '/admin/kyc',
    kycReview: (userId: string) => `/admin/kyc/${userId}`,
    emails: '/admin/emails',
    deposits: '/admin/deposits',
    deposit: (depositId: string) => `/admin/deposits/${depositId}`,
    referrals: '/admin/referrals',
    withdrawals: '/admin/withdrawals',
    withdrawal: (withdrawalId: string) => `/admin/withdrawals/${withdrawalId}`,
    trades: '/admin/trades',
    newTrade: '/admin/trades/new',
    trade: (tradeId: string) => `/admin/trades/${tradeId}`,
    dailyReturn: '/admin/daily-return',
    dailyReturnRun: (runId: string) => `/admin/daily-return/${runId}`,
    /** @deprecated Alias of dailyReturn — prefer dailyReturn. Redirected in Next config. */
    returns: '/admin/daily-return',
    notifications: '/admin/notifications',
    broadcast: '/admin/broadcast',
    auditLog: '/admin/audit-log',
    reports: '/admin/reports',
    reportLibrary: '/admin/report-library',
    /** Admin Frontend Management — section map for the marketing site */
    frontendManagement: '/admin/frontend-management',
    /** CMS downloads / reports manager */
    downloads: '/admin/downloads',
    /** Admin OS — CMS & marketing control */
    cms: {
      landing: '/admin/cms/landing',
      content: '/admin/cms/content',
      media: '/admin/cms/media',
      site: '/admin/cms/site',
      backup: '/admin/cms/backup',
      platform: '/admin/cms/platform',
    },
    ticker: '/admin/ticker',
    performance: '/admin/performance',
    activity: '/admin/activity',
    announcements: '/admin/announcements',
    wallets: '/admin/wallets',
    support: '/admin/support',
    featureToggles: '/admin/feature-toggles',
    emailTemplates: '/admin/email-templates',
    systemHealth: '/admin/system-health',
    search: '/admin/search',
    activityCenter: '/admin/activity-center',
    settings: {
      platform: '/admin/settings/platform',
      paymentMethods: '/admin/settings/payment-methods',
      staff: '/admin/settings/staff',
      emailTemplates: '/admin/settings/email-templates',
      general: '/admin/settings/general',
      security: '/admin/settings/security',
      roles: '/admin/settings/roles',
      global: '/admin/settings/global',
      handover: '/admin/settings/handover',
    },
  },

  /**
   * Isolated Sales Portal. Salesman cookies are not investor `mfx_at`.
   * Owner pages reuse existing Admin/Super Admin authentication.
   */
  sales: {
    login: '/sales/login',
    root: '/sales',
    dashboard: '/sales/dashboard',
    network: '/sales/network',
    customers: '/sales/customers',
    customer: (userId: string) => `/sales/customers/${userId}`,
    investments: '/sales/investments',
    performance: '/sales/performance',
    referral: '/sales/referral',
    profile: '/sales/profile',
    owner: {
      root: '/sales/owner',
      salesmen: '/sales/owner/salesmen',
      salesman: (salesmanId: string) => `/sales/owner/salesmen/${salesmanId}`,
      salesmanNetwork: (salesmanId: string) => `/sales/owner/salesmen/${salesmanId}/network`,
      networks: '/sales/owner/networks',
      reports: '/sales/owner/reports',
    },
  },
} as const

/** API paths, relative to the versioned base URL. */
export const API_ROUTES = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/verify-email/resend',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    google: '/auth/google',
    googleCallback: '/auth/google/callback',
    sessions: '/auth/sessions',
  },
  wallet: {
    root: '/wallet',
    summary: '/wallet/summary',
    transactions: '/wallet/transactions',
    history: '/wallet/history',
  },
  deposits: {
    root: '/deposits',
    methods: '/deposits/methods',
    oxapay: '/deposits/oxapay',
    oxapayStatus: '/deposits/oxapay/status',
    cancel: (id: string) => `/deposits/${id}/cancel`,
    proof: (id: string) => `/deposits/${id}/proof`,
    /** Authenticated binary stream for payment proof preview/download. */
    proofFile: (id: string) => `/deposits/${id}/proof-file`,
  },
  withdrawals: {
    root: '/withdrawals',
    limits: '/withdrawals/limits',
    methods: '/withdrawals/methods',
    method: (id: string) => `/withdrawals/methods/${id}`,
    methodDefault: (id: string) => `/withdrawals/methods/${id}/default`,
    otp: '/withdrawals/otp',
    cancel: (id: string) => `/withdrawals/${id}/cancel`,
  },
  activity: {
    root: '/activity',
  },
  transactions: { root: '/transactions' },
  markets: {
    quotes: '/markets/quotes',
    status: '/markets/status',
  },
  trades: {
    root: '/trades',
    pairs: '/trades/pairs',
    stats: '/trades/stats',
    public: '/trades/public',
    byId: (id: string) => `/trades/${id}`,
  },
  performance: {
    summary: '/performance/summary',
    series: '/performance/series',
    monthly: '/performance/monthly',
    yearly: '/performance/yearly',
    distributions: '/performance/distributions',
    public: '/performance/public',
  },
  returns: { root: '/returns' },
  portfolio: { root: '/portfolio' },
  notifications: {
    root: '/notifications',
    unreadCount: '/notifications/unread-count',
    readAll: '/notifications/read-all',
    read: (id: string) => `/notifications/${id}/read`,
  },
  settings: { public: '/settings/public', me: '/settings/me' },
  currency: {
    rates: '/currency/rates',
    convert: '/currency/convert',
    me: '/currency/me',
  },
  profile: {
    root: '/profile',
    avatar: '/profile/avatar',
    sessions: '/profile/sessions',
  },
  referrals: {
    summary: '/referrals/summary',
    network: '/referrals/network',
    rewards: '/referrals/rewards',
    redeem: (id: string) => `/referrals/rewards/${id}/redeem`,
  },
  progressShare: {
    link: '/progress-share/link',
    snapshot: '/progress-share/snapshot',
    image: '/progress-share/image',
  },
  kyc: {
    root: '/kyc',
    me: '/kyc/me',
    status: '/kyc/status',
    submit: '/kyc/submit',
    upload: '/kyc/upload',
    update: '/kyc/update',
    history: '/kyc/history',
    documents: '/kyc/documents',
    document: (id: string) => `/kyc/document/${id}`,
  },
  support: {
    tickets: '/support/tickets',
    ticket: (id: string) => `/support/tickets/${id}`,
    messages: (id: string) => `/support/tickets/${id}/messages`,
  },
  reports: { root: '/reports', export: '/reports/export' },
  webhooks: {
    payments: '/webhooks/payments',
  },
  cms: {
    public: '/cms/public',
    landing: '/cms/landing',
    platform: '/cms/platform',
    frontend: '/cms/frontend',
    downloads: '/cms/downloads',
    downloadsPublic: '/cms/downloads/public',
    rollback: (revisionId: string) => `/cms/public/revisions/${revisionId}/rollback`,
  },
  admin: {
    root: '/admin',
    health: '/admin/health',
    search: '/admin/search',
    activity: '/admin/activity',
    dashboard: '/admin/dashboard',
    dashboardOps: '/admin/dashboard/ops',
    users: '/admin/users',
    kyc: '/admin/kyc',
    deposits: '/admin/deposits',
    depositProof: (id: string) => `/admin/deposits/${id}/proof`,
    referrals: {
      summary: '/admin/referrals/summary',
      rewards: '/admin/referrals/rewards',
      reward: (id: string) => `/admin/referrals/rewards/${id}`,
      relationships: '/admin/referrals/relationships',
    },
    withdrawals: '/admin/withdrawals',
    wallets: '/admin/wallets',
    paymentMethods: '/admin/payment-methods',
    paymentMethodsReorder: '/admin/payment-methods/reorder',
    walletAddresses: '/admin/wallet-addresses',
    ledger: '/admin/ledger',
    financeMetrics: '/admin/finance/metrics',
    financeReconciliation: '/admin/finance/reconciliation',
    financeWebhooks: '/admin/finance/webhooks',
    trades: '/admin/trades',
    tradeAllocate: '/admin/trades/allocate',
    tradePublish: '/admin/trades/publish',
    performance: '/admin/performance',
    returns: '/admin/returns',
    notifications: '/admin/notifications',
    support: '/admin/support',
    audit: '/admin/audit',
    settings: '/admin/settings',
    featureFlags: '/admin/feature-flags',
    roles: '/admin/roles',
    media: '/admin/media',
    backups: '/admin/backups',
    handoverPreview: '/admin/handover/reset/preview',
    handoverReset: '/admin/handover/reset',
    emails: '/admin/emails',
    emailTemplates: '/admin/email-templates',
    broadcasts: '/admin/broadcasts',
    announcements: '/admin/announcements',
    reports: '/admin/reports',
    opsMetrics: '/admin/ops/metrics',
  },
  sales: {
    auth: {
      login: '/sales/auth/login',
      logout: '/sales/auth/logout',
      refresh: '/sales/auth/refresh',
    },
    me: '/sales/me',
    meNetwork: '/sales/me/network',
    meNetworkMembers: '/sales/me/network/members',
    meNetworkMember: (userId: string) => `/sales/me/network/members/${userId}`,
    meNetworkSummary: '/sales/me/network/summary',
    ownerSalesmen: '/sales/owner/salesmen',
    ownerNetwork: (salesmanId: string) => `/sales/owner/salesmen/${salesmanId}/network`,
    ownerNetworkMembers: (salesmanId: string) =>
      `/sales/owner/salesmen/${salesmanId}/network/members`,
    ownerNetworkMember: (salesmanId: string, userId: string) =>
      `/sales/owner/salesmen/${salesmanId}/network/members/${userId}`,
    ownerNetworkSummary: (salesmanId: string) =>
      `/sales/owner/salesmen/${salesmanId}/network/summary`,
  },
} as const
